/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../context"
import type { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  ProductInProductListListRelationFilter: { // input type
    every?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
    none?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
    some?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
  }
  ProductInProductListWhereInput: { // input type
    AND?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    NOT?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    OR?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    exclusive?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    exclusiveComments?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    minimumOrderQuantity?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    product?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    productId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productList?: NexusGenInputs['ProductListWhereInput'] | null; // ProductListWhereInput
    productListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ProductListWhereInput: { // input type
    AND?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    NOT?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    OR?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    products?: NexusGenInputs['ProductInProductListListRelationFilter'] | null; // ProductInProductListListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductListWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  ProductWhereInput: { // input type
    AND?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    NOT?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    OR?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    colorwayName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    pc9?: NexusGenInputs['StringFilter'] | null; // StringFilter
    productLists?: NexusGenInputs['ProductInProductListListRelationFilter'] | null; // ProductInProductListListRelationFilter
  }
  ProductWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Product: { // root type
    colorwayName: string; // String!
    pc9: string; // String!
  }
  ProductInProductList: { // root type
    exclusive?: string | null; // String
    exclusiveComments?: string | null; // String
    minimumOrderQuantity?: number | null; // Int
  }
  ProductList: { // root type
    id: number; // Int!
    title: string; // String!
  }
  ProductListProduct: { // root type
    product: NexusGenRootTypes['Product']; // Product!
    productInProductList: NexusGenRootTypes['ProductInProductList']; // ProductInProductList!
  }
  ProductListProductConnection: { // root type
    edges: NexusGenRootTypes['ProductListProductEdge'][]; // [ProductListProductEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  ProductListProductEdge: { // root type
    cursor: string; // String!
    node: NexusGenRootTypes['ProductListProduct']; // ProductListProduct!
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Product: { // field return type
    colorwayName: string; // String!
    id: string; // ID!
    pc9: string; // String!
  }
  ProductInProductList: { // field return type
    exclusive: string | null; // String
    exclusiveComments: string | null; // String
    id: string; // ID!
    minimumOrderQuantity: number | null; // Int
  }
  ProductList: { // field return type
    id: number; // Int!
    productListProductConnection: NexusGenRootTypes['ProductListProductConnection']; // ProductListProductConnection!
    title: string; // String!
  }
  ProductListProduct: { // field return type
    id: string; // ID!
    product: NexusGenRootTypes['Product']; // Product!
    productInProductList: NexusGenRootTypes['ProductInProductList']; // ProductInProductList!
  }
  ProductListProductConnection: { // field return type
    edges: NexusGenRootTypes['ProductListProductEdge'][]; // [ProductListProductEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  ProductListProductEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['ProductListProduct']; // ProductListProduct!
  }
  Query: { // field return type
    product: NexusGenRootTypes['Product'] | null; // Product
    productList: NexusGenRootTypes['ProductList'] | null; // ProductList
    productLists: NexusGenRootTypes['ProductList'][]; // [ProductList!]!
    products: NexusGenRootTypes['Product'][]; // [Product!]!
  }
}

export interface NexusGenFieldTypeNames {
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Product: { // field return type name
    colorwayName: 'String'
    id: 'ID'
    pc9: 'String'
  }
  ProductInProductList: { // field return type name
    exclusive: 'String'
    exclusiveComments: 'String'
    id: 'ID'
    minimumOrderQuantity: 'Int'
  }
  ProductList: { // field return type name
    id: 'Int'
    productListProductConnection: 'ProductListProductConnection'
    title: 'String'
  }
  ProductListProduct: { // field return type name
    id: 'ID'
    product: 'Product'
    productInProductList: 'ProductInProductList'
  }
  ProductListProductConnection: { // field return type name
    edges: 'ProductListProductEdge'
    pageInfo: 'PageInfo'
  }
  ProductListProductEdge: { // field return type name
    cursor: 'String'
    node: 'ProductListProduct'
  }
  Query: { // field return type name
    product: 'Product'
    productList: 'ProductList'
    productLists: 'ProductList'
    products: 'Product'
  }
}

export interface NexusGenArgTypes {
  ProductList: {
    productListProductConnection: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    product: { // args
      where: NexusGenInputs['ProductWhereUniqueInput']; // ProductWhereUniqueInput!
    }
    productList: { // args
      where: NexusGenInputs['ProductListWhereUniqueInput']; // ProductListWhereUniqueInput!
    }
    productLists: { // args
      after?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
      before?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['ProductListWhereInput'] | null; // ProductListWhereInput
    }
    products: { // args
      after?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
      before?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}