/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./../context"
import type { core, connectionPluginCore } from "nexus"

declare global {
  interface NexusGenCustomOutputMethods<TypeName extends string> {
    /**
     * Adds a Relay-style connection to the type, with numerous options for configuration
     *
     * @see https://nexusjs.org/docs/plugins/connection
     */
    connectionField<FieldName extends string>(
      fieldName: FieldName,
      config: connectionPluginCore.ConnectionFieldConfig<TypeName, FieldName>
    ): void
  }
}
declare global {
  interface NexusGenCustomOutputProperties<TypeName extends string> {
    crud: NexusPrisma<TypeName, 'crud'>
    model: NexusPrisma<TypeName, 'model'>
  }
}

declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
  ChannelCreateNestedOneWithoutDistributionInput: { // input type
    connect?: NexusGenInputs['ChannelWhereUniqueInput'] | null; // ChannelWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ChannelCreateOrConnectWithoutDistributionInput'] | null; // ChannelCreateOrConnectWithoutDistributionInput
    create?: NexusGenInputs['ChannelCreateWithoutDistributionInput'] | null; // ChannelCreateWithoutDistributionInput
  }
  ChannelCreateNestedOneWithoutProductListsInput: { // input type
    connect?: NexusGenInputs['ChannelWhereUniqueInput'] | null; // ChannelWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ChannelCreateOrConnectWithoutProductListsInput'] | null; // ChannelCreateOrConnectWithoutProductListsInput
    create?: NexusGenInputs['ChannelCreateWithoutProductListsInput'] | null; // ChannelCreateWithoutProductListsInput
  }
  ChannelCreateOrConnectWithoutDistributionInput: { // input type
    create: NexusGenInputs['ChannelCreateWithoutDistributionInput']; // ChannelCreateWithoutDistributionInput!
    where: NexusGenInputs['ChannelWhereUniqueInput']; // ChannelWhereUniqueInput!
  }
  ChannelCreateOrConnectWithoutProductListsInput: { // input type
    create: NexusGenInputs['ChannelCreateWithoutProductListsInput']; // ChannelCreateWithoutProductListsInput!
    where: NexusGenInputs['ChannelWhereUniqueInput']; // ChannelWhereUniqueInput!
  }
  ChannelCreateWithoutDistributionInput: { // input type
    name: string; // String!
    productLists?: NexusGenInputs['ChannelInProductListCreateNestedManyWithoutChannelInput'] | null; // ChannelInProductListCreateNestedManyWithoutChannelInput
  }
  ChannelCreateWithoutProductListsInput: { // input type
    Distribution?: NexusGenInputs['DistributionCreateNestedManyWithoutChannelInput'] | null; // DistributionCreateNestedManyWithoutChannelInput
    name: string; // String!
  }
  ChannelInProductListChannelIdProductListIdCompoundUniqueInput: { // input type
    channelId: number; // Int!
    productListId: number; // Int!
  }
  ChannelInProductListCreateManyChannelInput: { // input type
    id?: number | null; // Int
    productListId: number; // Int!
  }
  ChannelInProductListCreateManyChannelInputEnvelope: { // input type
    data?: NexusGenInputs['ChannelInProductListCreateManyChannelInput'][] | null; // [ChannelInProductListCreateManyChannelInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  ChannelInProductListCreateManyProductListInput: { // input type
    channelId: number; // Int!
    id?: number | null; // Int
  }
  ChannelInProductListCreateManyProductListInputEnvelope: { // input type
    data?: NexusGenInputs['ChannelInProductListCreateManyProductListInput'][] | null; // [ChannelInProductListCreateManyProductListInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  ChannelInProductListCreateNestedManyWithoutChannelInput: { // input type
    connect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ChannelInProductListCreateOrConnectWithoutChannelInput'][] | null; // [ChannelInProductListCreateOrConnectWithoutChannelInput!]
    create?: NexusGenInputs['ChannelInProductListCreateWithoutChannelInput'][] | null; // [ChannelInProductListCreateWithoutChannelInput!]
    createMany?: NexusGenInputs['ChannelInProductListCreateManyChannelInputEnvelope'] | null; // ChannelInProductListCreateManyChannelInputEnvelope
  }
  ChannelInProductListCreateNestedManyWithoutProductListInput: { // input type
    connect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ChannelInProductListCreateOrConnectWithoutProductListInput'][] | null; // [ChannelInProductListCreateOrConnectWithoutProductListInput!]
    create?: NexusGenInputs['ChannelInProductListCreateWithoutProductListInput'][] | null; // [ChannelInProductListCreateWithoutProductListInput!]
    createMany?: NexusGenInputs['ChannelInProductListCreateManyProductListInputEnvelope'] | null; // ChannelInProductListCreateManyProductListInputEnvelope
  }
  ChannelInProductListCreateOrConnectWithoutChannelInput: { // input type
    create: NexusGenInputs['ChannelInProductListCreateWithoutChannelInput']; // ChannelInProductListCreateWithoutChannelInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListCreateOrConnectWithoutProductListInput: { // input type
    create: NexusGenInputs['ChannelInProductListCreateWithoutProductListInput']; // ChannelInProductListCreateWithoutProductListInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListCreateWithoutChannelInput: { // input type
    productList: NexusGenInputs['ProductListCreateNestedOneWithoutChannelsInput']; // ProductListCreateNestedOneWithoutChannelsInput!
  }
  ChannelInProductListCreateWithoutProductListInput: { // input type
    channel: NexusGenInputs['ChannelCreateNestedOneWithoutProductListsInput']; // ChannelCreateNestedOneWithoutProductListsInput!
  }
  ChannelInProductListListRelationFilter: { // input type
    every?: NexusGenInputs['ChannelInProductListWhereInput'] | null; // ChannelInProductListWhereInput
    none?: NexusGenInputs['ChannelInProductListWhereInput'] | null; // ChannelInProductListWhereInput
    some?: NexusGenInputs['ChannelInProductListWhereInput'] | null; // ChannelInProductListWhereInput
  }
  ChannelInProductListScalarWhereInput: { // input type
    AND?: NexusGenInputs['ChannelInProductListScalarWhereInput'][] | null; // [ChannelInProductListScalarWhereInput!]
    NOT?: NexusGenInputs['ChannelInProductListScalarWhereInput'][] | null; // [ChannelInProductListScalarWhereInput!]
    OR?: NexusGenInputs['ChannelInProductListScalarWhereInput'][] | null; // [ChannelInProductListScalarWhereInput!]
    channelId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ChannelInProductListUpdateManyMutationInput: { // input type
    _dummy_field?: number | null; // Int
  }
  ChannelInProductListUpdateManyWithWhereWithoutChannelInput: { // input type
    data: NexusGenInputs['ChannelInProductListUpdateManyMutationInput']; // ChannelInProductListUpdateManyMutationInput!
    where: NexusGenInputs['ChannelInProductListScalarWhereInput']; // ChannelInProductListScalarWhereInput!
  }
  ChannelInProductListUpdateManyWithWhereWithoutProductListInput: { // input type
    data: NexusGenInputs['ChannelInProductListUpdateManyMutationInput']; // ChannelInProductListUpdateManyMutationInput!
    where: NexusGenInputs['ChannelInProductListScalarWhereInput']; // ChannelInProductListScalarWhereInput!
  }
  ChannelInProductListUpdateManyWithoutChannelInput: { // input type
    connect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ChannelInProductListCreateOrConnectWithoutChannelInput'][] | null; // [ChannelInProductListCreateOrConnectWithoutChannelInput!]
    create?: NexusGenInputs['ChannelInProductListCreateWithoutChannelInput'][] | null; // [ChannelInProductListCreateWithoutChannelInput!]
    createMany?: NexusGenInputs['ChannelInProductListCreateManyChannelInputEnvelope'] | null; // ChannelInProductListCreateManyChannelInputEnvelope
    delete?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ChannelInProductListScalarWhereInput'][] | null; // [ChannelInProductListScalarWhereInput!]
    disconnect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    set?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    update?: NexusGenInputs['ChannelInProductListUpdateWithWhereUniqueWithoutChannelInput'][] | null; // [ChannelInProductListUpdateWithWhereUniqueWithoutChannelInput!]
    updateMany?: NexusGenInputs['ChannelInProductListUpdateManyWithWhereWithoutChannelInput'][] | null; // [ChannelInProductListUpdateManyWithWhereWithoutChannelInput!]
    upsert?: NexusGenInputs['ChannelInProductListUpsertWithWhereUniqueWithoutChannelInput'][] | null; // [ChannelInProductListUpsertWithWhereUniqueWithoutChannelInput!]
  }
  ChannelInProductListUpdateManyWithoutProductListInput: { // input type
    connect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ChannelInProductListCreateOrConnectWithoutProductListInput'][] | null; // [ChannelInProductListCreateOrConnectWithoutProductListInput!]
    create?: NexusGenInputs['ChannelInProductListCreateWithoutProductListInput'][] | null; // [ChannelInProductListCreateWithoutProductListInput!]
    createMany?: NexusGenInputs['ChannelInProductListCreateManyProductListInputEnvelope'] | null; // ChannelInProductListCreateManyProductListInputEnvelope
    delete?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ChannelInProductListScalarWhereInput'][] | null; // [ChannelInProductListScalarWhereInput!]
    disconnect?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    set?: NexusGenInputs['ChannelInProductListWhereUniqueInput'][] | null; // [ChannelInProductListWhereUniqueInput!]
    update?: NexusGenInputs['ChannelInProductListUpdateWithWhereUniqueWithoutProductListInput'][] | null; // [ChannelInProductListUpdateWithWhereUniqueWithoutProductListInput!]
    updateMany?: NexusGenInputs['ChannelInProductListUpdateManyWithWhereWithoutProductListInput'][] | null; // [ChannelInProductListUpdateManyWithWhereWithoutProductListInput!]
    upsert?: NexusGenInputs['ChannelInProductListUpsertWithWhereUniqueWithoutProductListInput'][] | null; // [ChannelInProductListUpsertWithWhereUniqueWithoutProductListInput!]
  }
  ChannelInProductListUpdateWithWhereUniqueWithoutChannelInput: { // input type
    data: NexusGenInputs['ChannelInProductListUpdateWithoutChannelInput']; // ChannelInProductListUpdateWithoutChannelInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListUpdateWithWhereUniqueWithoutProductListInput: { // input type
    data: NexusGenInputs['ChannelInProductListUpdateWithoutProductListInput']; // ChannelInProductListUpdateWithoutProductListInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListUpdateWithoutChannelInput: { // input type
    productList?: NexusGenInputs['ProductListUpdateOneRequiredWithoutChannelsInput'] | null; // ProductListUpdateOneRequiredWithoutChannelsInput
  }
  ChannelInProductListUpdateWithoutProductListInput: { // input type
    channel?: NexusGenInputs['ChannelUpdateOneRequiredWithoutProductListsInput'] | null; // ChannelUpdateOneRequiredWithoutProductListsInput
  }
  ChannelInProductListUpsertWithWhereUniqueWithoutChannelInput: { // input type
    create: NexusGenInputs['ChannelInProductListCreateWithoutChannelInput']; // ChannelInProductListCreateWithoutChannelInput!
    update: NexusGenInputs['ChannelInProductListUpdateWithoutChannelInput']; // ChannelInProductListUpdateWithoutChannelInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListUpsertWithWhereUniqueWithoutProductListInput: { // input type
    create: NexusGenInputs['ChannelInProductListCreateWithoutProductListInput']; // ChannelInProductListCreateWithoutProductListInput!
    update: NexusGenInputs['ChannelInProductListUpdateWithoutProductListInput']; // ChannelInProductListUpdateWithoutProductListInput!
    where: NexusGenInputs['ChannelInProductListWhereUniqueInput']; // ChannelInProductListWhereUniqueInput!
  }
  ChannelInProductListWhereInput: { // input type
    AND?: NexusGenInputs['ChannelInProductListWhereInput'][] | null; // [ChannelInProductListWhereInput!]
    NOT?: NexusGenInputs['ChannelInProductListWhereInput'][] | null; // [ChannelInProductListWhereInput!]
    OR?: NexusGenInputs['ChannelInProductListWhereInput'][] | null; // [ChannelInProductListWhereInput!]
    channel?: NexusGenInputs['ChannelWhereInput'] | null; // ChannelWhereInput
    channelId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productList?: NexusGenInputs['ProductListWhereInput'] | null; // ProductListWhereInput
    productListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ChannelInProductListWhereUniqueInput: { // input type
    channelId_productListId?: NexusGenInputs['ChannelInProductListChannelIdProductListIdCompoundUniqueInput'] | null; // ChannelInProductListChannelIdProductListIdCompoundUniqueInput
    id?: number | null; // Int
  }
  ChannelUpdateOneRequiredWithoutDistributionInput: { // input type
    connect?: NexusGenInputs['ChannelWhereUniqueInput'] | null; // ChannelWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ChannelCreateOrConnectWithoutDistributionInput'] | null; // ChannelCreateOrConnectWithoutDistributionInput
    create?: NexusGenInputs['ChannelCreateWithoutDistributionInput'] | null; // ChannelCreateWithoutDistributionInput
    update?: NexusGenInputs['ChannelUpdateWithoutDistributionInput'] | null; // ChannelUpdateWithoutDistributionInput
    upsert?: NexusGenInputs['ChannelUpsertWithoutDistributionInput'] | null; // ChannelUpsertWithoutDistributionInput
  }
  ChannelUpdateOneRequiredWithoutProductListsInput: { // input type
    connect?: NexusGenInputs['ChannelWhereUniqueInput'] | null; // ChannelWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ChannelCreateOrConnectWithoutProductListsInput'] | null; // ChannelCreateOrConnectWithoutProductListsInput
    create?: NexusGenInputs['ChannelCreateWithoutProductListsInput'] | null; // ChannelCreateWithoutProductListsInput
    update?: NexusGenInputs['ChannelUpdateWithoutProductListsInput'] | null; // ChannelUpdateWithoutProductListsInput
    upsert?: NexusGenInputs['ChannelUpsertWithoutProductListsInput'] | null; // ChannelUpsertWithoutProductListsInput
  }
  ChannelUpdateWithoutDistributionInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    productLists?: NexusGenInputs['ChannelInProductListUpdateManyWithoutChannelInput'] | null; // ChannelInProductListUpdateManyWithoutChannelInput
  }
  ChannelUpdateWithoutProductListsInput: { // input type
    Distribution?: NexusGenInputs['DistributionUpdateManyWithoutChannelInput'] | null; // DistributionUpdateManyWithoutChannelInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ChannelUpsertWithoutDistributionInput: { // input type
    create: NexusGenInputs['ChannelCreateWithoutDistributionInput']; // ChannelCreateWithoutDistributionInput!
    update: NexusGenInputs['ChannelUpdateWithoutDistributionInput']; // ChannelUpdateWithoutDistributionInput!
  }
  ChannelUpsertWithoutProductListsInput: { // input type
    create: NexusGenInputs['ChannelCreateWithoutProductListsInput']; // ChannelCreateWithoutProductListsInput!
    update: NexusGenInputs['ChannelUpdateWithoutProductListsInput']; // ChannelUpdateWithoutProductListsInput!
  }
  ChannelWhereInput: { // input type
    AND?: NexusGenInputs['ChannelWhereInput'][] | null; // [ChannelWhereInput!]
    Distribution?: NexusGenInputs['DistributionListRelationFilter'] | null; // DistributionListRelationFilter
    NOT?: NexusGenInputs['ChannelWhereInput'][] | null; // [ChannelWhereInput!]
    OR?: NexusGenInputs['ChannelWhereInput'][] | null; // [ChannelWhereInput!]
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    productLists?: NexusGenInputs['ChannelInProductListListRelationFilter'] | null; // ChannelInProductListListRelationFilter
  }
  ChannelWhereUniqueInput: { // input type
    id?: number | null; // Int
    name?: string | null; // String
  }
  DistributionCreateManyChannelInput: { // input type
    id?: number | null; // Int
    name: string; // String!
  }
  DistributionCreateManyChannelInputEnvelope: { // input type
    data?: NexusGenInputs['DistributionCreateManyChannelInput'][] | null; // [DistributionCreateManyChannelInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  DistributionCreateNestedManyWithoutChannelInput: { // input type
    connect?: NexusGenInputs['DistributionWhereUniqueInput'][] | null; // [DistributionWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionCreateOrConnectWithoutChannelInput'][] | null; // [DistributionCreateOrConnectWithoutChannelInput!]
    create?: NexusGenInputs['DistributionCreateWithoutChannelInput'][] | null; // [DistributionCreateWithoutChannelInput!]
    createMany?: NexusGenInputs['DistributionCreateManyChannelInputEnvelope'] | null; // DistributionCreateManyChannelInputEnvelope
  }
  DistributionCreateNestedOneWithoutProductInProductListsInput: { // input type
    connect?: NexusGenInputs['DistributionWhereUniqueInput'] | null; // DistributionWhereUniqueInput
    connectOrCreate?: NexusGenInputs['DistributionCreateOrConnectWithoutProductInProductListsInput'] | null; // DistributionCreateOrConnectWithoutProductInProductListsInput
    create?: NexusGenInputs['DistributionCreateWithoutProductInProductListsInput'] | null; // DistributionCreateWithoutProductInProductListsInput
  }
  DistributionCreateOrConnectWithoutChannelInput: { // input type
    create: NexusGenInputs['DistributionCreateWithoutChannelInput']; // DistributionCreateWithoutChannelInput!
    where: NexusGenInputs['DistributionWhereUniqueInput']; // DistributionWhereUniqueInput!
  }
  DistributionCreateOrConnectWithoutProductInProductListsInput: { // input type
    create: NexusGenInputs['DistributionCreateWithoutProductInProductListsInput']; // DistributionCreateWithoutProductInProductListsInput!
    where: NexusGenInputs['DistributionWhereUniqueInput']; // DistributionWhereUniqueInput!
  }
  DistributionCreateWithoutChannelInput: { // input type
    name: string; // String!
    productInProductLists?: NexusGenInputs['DistributionForProductInProductListCreateNestedManyWithoutDistributionInput'] | null; // DistributionForProductInProductListCreateNestedManyWithoutDistributionInput
  }
  DistributionCreateWithoutProductInProductListsInput: { // input type
    channel: NexusGenInputs['ChannelCreateNestedOneWithoutDistributionInput']; // ChannelCreateNestedOneWithoutDistributionInput!
    name: string; // String!
  }
  DistributionForProductInProductListCreateManyDistributionInput: { // input type
    id?: number | null; // Int
    productInProductListId: number; // Int!
  }
  DistributionForProductInProductListCreateManyDistributionInputEnvelope: { // input type
    data?: NexusGenInputs['DistributionForProductInProductListCreateManyDistributionInput'][] | null; // [DistributionForProductInProductListCreateManyDistributionInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  DistributionForProductInProductListCreateManyProductInProductListInput: { // input type
    distributionId: number; // Int!
    id?: number | null; // Int
  }
  DistributionForProductInProductListCreateManyProductInProductListInputEnvelope: { // input type
    data?: NexusGenInputs['DistributionForProductInProductListCreateManyProductInProductListInput'][] | null; // [DistributionForProductInProductListCreateManyProductInProductListInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  DistributionForProductInProductListCreateNestedManyWithoutDistributionInput: { // input type
    connect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionForProductInProductListCreateOrConnectWithoutDistributionInput'][] | null; // [DistributionForProductInProductListCreateOrConnectWithoutDistributionInput!]
    create?: NexusGenInputs['DistributionForProductInProductListCreateWithoutDistributionInput'][] | null; // [DistributionForProductInProductListCreateWithoutDistributionInput!]
    createMany?: NexusGenInputs['DistributionForProductInProductListCreateManyDistributionInputEnvelope'] | null; // DistributionForProductInProductListCreateManyDistributionInputEnvelope
  }
  DistributionForProductInProductListCreateNestedManyWithoutProductInProductListInput: { // input type
    connect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionForProductInProductListCreateOrConnectWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListCreateOrConnectWithoutProductInProductListInput!]
    create?: NexusGenInputs['DistributionForProductInProductListCreateWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListCreateWithoutProductInProductListInput!]
    createMany?: NexusGenInputs['DistributionForProductInProductListCreateManyProductInProductListInputEnvelope'] | null; // DistributionForProductInProductListCreateManyProductInProductListInputEnvelope
  }
  DistributionForProductInProductListCreateOrConnectWithoutDistributionInput: { // input type
    create: NexusGenInputs['DistributionForProductInProductListCreateWithoutDistributionInput']; // DistributionForProductInProductListCreateWithoutDistributionInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListCreateOrConnectWithoutProductInProductListInput: { // input type
    create: NexusGenInputs['DistributionForProductInProductListCreateWithoutProductInProductListInput']; // DistributionForProductInProductListCreateWithoutProductInProductListInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListCreateWithoutDistributionInput: { // input type
    productInProductList: NexusGenInputs['ProductInProductListCreateNestedOneWithoutDistributionsInput']; // ProductInProductListCreateNestedOneWithoutDistributionsInput!
  }
  DistributionForProductInProductListCreateWithoutProductInProductListInput: { // input type
    distribution: NexusGenInputs['DistributionCreateNestedOneWithoutProductInProductListsInput']; // DistributionCreateNestedOneWithoutProductInProductListsInput!
  }
  DistributionForProductInProductListDistributionIdProductInProductListIdCompoundUniqueInput: { // input type
    distributionId: number; // Int!
    productInProductListId: number; // Int!
  }
  DistributionForProductInProductListListRelationFilter: { // input type
    every?: NexusGenInputs['DistributionForProductInProductListWhereInput'] | null; // DistributionForProductInProductListWhereInput
    none?: NexusGenInputs['DistributionForProductInProductListWhereInput'] | null; // DistributionForProductInProductListWhereInput
    some?: NexusGenInputs['DistributionForProductInProductListWhereInput'] | null; // DistributionForProductInProductListWhereInput
  }
  DistributionForProductInProductListScalarWhereInput: { // input type
    AND?: NexusGenInputs['DistributionForProductInProductListScalarWhereInput'][] | null; // [DistributionForProductInProductListScalarWhereInput!]
    NOT?: NexusGenInputs['DistributionForProductInProductListScalarWhereInput'][] | null; // [DistributionForProductInProductListScalarWhereInput!]
    OR?: NexusGenInputs['DistributionForProductInProductListScalarWhereInput'][] | null; // [DistributionForProductInProductListScalarWhereInput!]
    distributionId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productInProductListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  DistributionForProductInProductListUpdateManyMutationInput: { // input type
    _dummy_field?: number | null; // Int
  }
  DistributionForProductInProductListUpdateManyWithWhereWithoutDistributionInput: { // input type
    data: NexusGenInputs['DistributionForProductInProductListUpdateManyMutationInput']; // DistributionForProductInProductListUpdateManyMutationInput!
    where: NexusGenInputs['DistributionForProductInProductListScalarWhereInput']; // DistributionForProductInProductListScalarWhereInput!
  }
  DistributionForProductInProductListUpdateManyWithWhereWithoutProductInProductListInput: { // input type
    data: NexusGenInputs['DistributionForProductInProductListUpdateManyMutationInput']; // DistributionForProductInProductListUpdateManyMutationInput!
    where: NexusGenInputs['DistributionForProductInProductListScalarWhereInput']; // DistributionForProductInProductListScalarWhereInput!
  }
  DistributionForProductInProductListUpdateManyWithoutDistributionInput: { // input type
    connect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionForProductInProductListCreateOrConnectWithoutDistributionInput'][] | null; // [DistributionForProductInProductListCreateOrConnectWithoutDistributionInput!]
    create?: NexusGenInputs['DistributionForProductInProductListCreateWithoutDistributionInput'][] | null; // [DistributionForProductInProductListCreateWithoutDistributionInput!]
    createMany?: NexusGenInputs['DistributionForProductInProductListCreateManyDistributionInputEnvelope'] | null; // DistributionForProductInProductListCreateManyDistributionInputEnvelope
    delete?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    deleteMany?: NexusGenInputs['DistributionForProductInProductListScalarWhereInput'][] | null; // [DistributionForProductInProductListScalarWhereInput!]
    disconnect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    set?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    update?: NexusGenInputs['DistributionForProductInProductListUpdateWithWhereUniqueWithoutDistributionInput'][] | null; // [DistributionForProductInProductListUpdateWithWhereUniqueWithoutDistributionInput!]
    updateMany?: NexusGenInputs['DistributionForProductInProductListUpdateManyWithWhereWithoutDistributionInput'][] | null; // [DistributionForProductInProductListUpdateManyWithWhereWithoutDistributionInput!]
    upsert?: NexusGenInputs['DistributionForProductInProductListUpsertWithWhereUniqueWithoutDistributionInput'][] | null; // [DistributionForProductInProductListUpsertWithWhereUniqueWithoutDistributionInput!]
  }
  DistributionForProductInProductListUpdateManyWithoutProductInProductListInput: { // input type
    connect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionForProductInProductListCreateOrConnectWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListCreateOrConnectWithoutProductInProductListInput!]
    create?: NexusGenInputs['DistributionForProductInProductListCreateWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListCreateWithoutProductInProductListInput!]
    createMany?: NexusGenInputs['DistributionForProductInProductListCreateManyProductInProductListInputEnvelope'] | null; // DistributionForProductInProductListCreateManyProductInProductListInputEnvelope
    delete?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    deleteMany?: NexusGenInputs['DistributionForProductInProductListScalarWhereInput'][] | null; // [DistributionForProductInProductListScalarWhereInput!]
    disconnect?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    set?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'][] | null; // [DistributionForProductInProductListWhereUniqueInput!]
    update?: NexusGenInputs['DistributionForProductInProductListUpdateWithWhereUniqueWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListUpdateWithWhereUniqueWithoutProductInProductListInput!]
    updateMany?: NexusGenInputs['DistributionForProductInProductListUpdateManyWithWhereWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListUpdateManyWithWhereWithoutProductInProductListInput!]
    upsert?: NexusGenInputs['DistributionForProductInProductListUpsertWithWhereUniqueWithoutProductInProductListInput'][] | null; // [DistributionForProductInProductListUpsertWithWhereUniqueWithoutProductInProductListInput!]
  }
  DistributionForProductInProductListUpdateWithWhereUniqueWithoutDistributionInput: { // input type
    data: NexusGenInputs['DistributionForProductInProductListUpdateWithoutDistributionInput']; // DistributionForProductInProductListUpdateWithoutDistributionInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListUpdateWithWhereUniqueWithoutProductInProductListInput: { // input type
    data: NexusGenInputs['DistributionForProductInProductListUpdateWithoutProductInProductListInput']; // DistributionForProductInProductListUpdateWithoutProductInProductListInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListUpdateWithoutDistributionInput: { // input type
    productInProductList?: NexusGenInputs['ProductInProductListUpdateOneRequiredWithoutDistributionsInput'] | null; // ProductInProductListUpdateOneRequiredWithoutDistributionsInput
  }
  DistributionForProductInProductListUpdateWithoutProductInProductListInput: { // input type
    distribution?: NexusGenInputs['DistributionUpdateOneRequiredWithoutProductInProductListsInput'] | null; // DistributionUpdateOneRequiredWithoutProductInProductListsInput
  }
  DistributionForProductInProductListUpsertWithWhereUniqueWithoutDistributionInput: { // input type
    create: NexusGenInputs['DistributionForProductInProductListCreateWithoutDistributionInput']; // DistributionForProductInProductListCreateWithoutDistributionInput!
    update: NexusGenInputs['DistributionForProductInProductListUpdateWithoutDistributionInput']; // DistributionForProductInProductListUpdateWithoutDistributionInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListUpsertWithWhereUniqueWithoutProductInProductListInput: { // input type
    create: NexusGenInputs['DistributionForProductInProductListCreateWithoutProductInProductListInput']; // DistributionForProductInProductListCreateWithoutProductInProductListInput!
    update: NexusGenInputs['DistributionForProductInProductListUpdateWithoutProductInProductListInput']; // DistributionForProductInProductListUpdateWithoutProductInProductListInput!
    where: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput']; // DistributionForProductInProductListWhereUniqueInput!
  }
  DistributionForProductInProductListWhereInput: { // input type
    AND?: NexusGenInputs['DistributionForProductInProductListWhereInput'][] | null; // [DistributionForProductInProductListWhereInput!]
    NOT?: NexusGenInputs['DistributionForProductInProductListWhereInput'][] | null; // [DistributionForProductInProductListWhereInput!]
    OR?: NexusGenInputs['DistributionForProductInProductListWhereInput'][] | null; // [DistributionForProductInProductListWhereInput!]
    distribution?: NexusGenInputs['DistributionWhereInput'] | null; // DistributionWhereInput
    distributionId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productInProductList?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
    productInProductListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  DistributionForProductInProductListWhereUniqueInput: { // input type
    distributionId_productInProductListId?: NexusGenInputs['DistributionForProductInProductListDistributionIdProductInProductListIdCompoundUniqueInput'] | null; // DistributionForProductInProductListDistributionIdProductInProductListIdCompoundUniqueInput
    id?: number | null; // Int
  }
  DistributionListRelationFilter: { // input type
    every?: NexusGenInputs['DistributionWhereInput'] | null; // DistributionWhereInput
    none?: NexusGenInputs['DistributionWhereInput'] | null; // DistributionWhereInput
    some?: NexusGenInputs['DistributionWhereInput'] | null; // DistributionWhereInput
  }
  DistributionNameChannelIdCompoundUniqueInput: { // input type
    channelId: number; // Int!
    name: string; // String!
  }
  DistributionScalarWhereInput: { // input type
    AND?: NexusGenInputs['DistributionScalarWhereInput'][] | null; // [DistributionScalarWhereInput!]
    NOT?: NexusGenInputs['DistributionScalarWhereInput'][] | null; // [DistributionScalarWhereInput!]
    OR?: NexusGenInputs['DistributionScalarWhereInput'][] | null; // [DistributionScalarWhereInput!]
    channelId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  DistributionUpdateManyMutationInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  DistributionUpdateManyWithWhereWithoutChannelInput: { // input type
    data: NexusGenInputs['DistributionUpdateManyMutationInput']; // DistributionUpdateManyMutationInput!
    where: NexusGenInputs['DistributionScalarWhereInput']; // DistributionScalarWhereInput!
  }
  DistributionUpdateManyWithoutChannelInput: { // input type
    connect?: NexusGenInputs['DistributionWhereUniqueInput'][] | null; // [DistributionWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['DistributionCreateOrConnectWithoutChannelInput'][] | null; // [DistributionCreateOrConnectWithoutChannelInput!]
    create?: NexusGenInputs['DistributionCreateWithoutChannelInput'][] | null; // [DistributionCreateWithoutChannelInput!]
    createMany?: NexusGenInputs['DistributionCreateManyChannelInputEnvelope'] | null; // DistributionCreateManyChannelInputEnvelope
    delete?: NexusGenInputs['DistributionWhereUniqueInput'][] | null; // [DistributionWhereUniqueInput!]
    deleteMany?: NexusGenInputs['DistributionScalarWhereInput'][] | null; // [DistributionScalarWhereInput!]
    disconnect?: NexusGenInputs['DistributionWhereUniqueInput'][] | null; // [DistributionWhereUniqueInput!]
    set?: NexusGenInputs['DistributionWhereUniqueInput'][] | null; // [DistributionWhereUniqueInput!]
    update?: NexusGenInputs['DistributionUpdateWithWhereUniqueWithoutChannelInput'][] | null; // [DistributionUpdateWithWhereUniqueWithoutChannelInput!]
    updateMany?: NexusGenInputs['DistributionUpdateManyWithWhereWithoutChannelInput'][] | null; // [DistributionUpdateManyWithWhereWithoutChannelInput!]
    upsert?: NexusGenInputs['DistributionUpsertWithWhereUniqueWithoutChannelInput'][] | null; // [DistributionUpsertWithWhereUniqueWithoutChannelInput!]
  }
  DistributionUpdateOneRequiredWithoutProductInProductListsInput: { // input type
    connect?: NexusGenInputs['DistributionWhereUniqueInput'] | null; // DistributionWhereUniqueInput
    connectOrCreate?: NexusGenInputs['DistributionCreateOrConnectWithoutProductInProductListsInput'] | null; // DistributionCreateOrConnectWithoutProductInProductListsInput
    create?: NexusGenInputs['DistributionCreateWithoutProductInProductListsInput'] | null; // DistributionCreateWithoutProductInProductListsInput
    update?: NexusGenInputs['DistributionUpdateWithoutProductInProductListsInput'] | null; // DistributionUpdateWithoutProductInProductListsInput
    upsert?: NexusGenInputs['DistributionUpsertWithoutProductInProductListsInput'] | null; // DistributionUpsertWithoutProductInProductListsInput
  }
  DistributionUpdateWithWhereUniqueWithoutChannelInput: { // input type
    data: NexusGenInputs['DistributionUpdateWithoutChannelInput']; // DistributionUpdateWithoutChannelInput!
    where: NexusGenInputs['DistributionWhereUniqueInput']; // DistributionWhereUniqueInput!
  }
  DistributionUpdateWithoutChannelInput: { // input type
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    productInProductLists?: NexusGenInputs['DistributionForProductInProductListUpdateManyWithoutDistributionInput'] | null; // DistributionForProductInProductListUpdateManyWithoutDistributionInput
  }
  DistributionUpdateWithoutProductInProductListsInput: { // input type
    channel?: NexusGenInputs['ChannelUpdateOneRequiredWithoutDistributionInput'] | null; // ChannelUpdateOneRequiredWithoutDistributionInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  DistributionUpsertWithWhereUniqueWithoutChannelInput: { // input type
    create: NexusGenInputs['DistributionCreateWithoutChannelInput']; // DistributionCreateWithoutChannelInput!
    update: NexusGenInputs['DistributionUpdateWithoutChannelInput']; // DistributionUpdateWithoutChannelInput!
    where: NexusGenInputs['DistributionWhereUniqueInput']; // DistributionWhereUniqueInput!
  }
  DistributionUpsertWithoutProductInProductListsInput: { // input type
    create: NexusGenInputs['DistributionCreateWithoutProductInProductListsInput']; // DistributionCreateWithoutProductInProductListsInput!
    update: NexusGenInputs['DistributionUpdateWithoutProductInProductListsInput']; // DistributionUpdateWithoutProductInProductListsInput!
  }
  DistributionWhereInput: { // input type
    AND?: NexusGenInputs['DistributionWhereInput'][] | null; // [DistributionWhereInput!]
    NOT?: NexusGenInputs['DistributionWhereInput'][] | null; // [DistributionWhereInput!]
    OR?: NexusGenInputs['DistributionWhereInput'][] | null; // [DistributionWhereInput!]
    channel?: NexusGenInputs['ChannelWhereInput'] | null; // ChannelWhereInput
    channelId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
    productInProductLists?: NexusGenInputs['DistributionForProductInProductListListRelationFilter'] | null; // DistributionForProductInProductListListRelationFilter
  }
  DistributionWhereUniqueInput: { // input type
    id?: number | null; // Int
    name?: string | null; // String
    name_channelId?: NexusGenInputs['DistributionNameChannelIdCompoundUniqueInput'] | null; // DistributionNameChannelIdCompoundUniqueInput
  }
  IntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  IntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntFilter'] | null; // NestedIntFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedIntNullableFilter: { // input type
    equals?: number | null; // Int
    gt?: number | null; // Int
    gte?: number | null; // Int
    in?: number[] | null; // [Int!]
    lt?: number | null; // Int
    lte?: number | null; // Int
    not?: NexusGenInputs['NestedIntNullableFilter'] | null; // NestedIntNullableFilter
    notIn?: number[] | null; // [Int!]
  }
  NestedStringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NestedStringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  NullableIntFieldUpdateOperationsInput: { // input type
    decrement?: number | null; // Int
    divide?: number | null; // Int
    increment?: number | null; // Int
    multiply?: number | null; // Int
    set?: number | null; // Int
  }
  NullableStringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  ProductCreateNestedOneWithoutProductListsInput: { // input type
    connect?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductCreateOrConnectWithoutProductListsInput'] | null; // ProductCreateOrConnectWithoutProductListsInput
    create?: NexusGenInputs['ProductCreateWithoutProductListsInput'] | null; // ProductCreateWithoutProductListsInput
  }
  ProductCreateOrConnectWithoutProductListsInput: { // input type
    create: NexusGenInputs['ProductCreateWithoutProductListsInput']; // ProductCreateWithoutProductListsInput!
    where: NexusGenInputs['ProductWhereUniqueInput']; // ProductWhereUniqueInput!
  }
  ProductCreateWithoutProductListsInput: { // input type
    colorwayName: string; // String!
    pc9: string; // String!
  }
  ProductInProductListCreateManyProductListInput: { // input type
    exclusive?: string | null; // String
    exclusiveComments?: string | null; // String
    id?: number | null; // Int
    minimumOrderQuantity?: number | null; // Int
    productId: number; // Int!
    productLifecycleGroupName?: string | null; // String
  }
  ProductInProductListCreateManyProductListInputEnvelope: { // input type
    data?: NexusGenInputs['ProductInProductListCreateManyProductListInput'][] | null; // [ProductInProductListCreateManyProductListInput!]
    skipDuplicates?: boolean | null; // Boolean
  }
  ProductInProductListCreateNestedManyWithoutProductListInput: { // input type
    connect?: NexusGenInputs['ProductInProductListWhereUniqueInput'][] | null; // [ProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ProductInProductListCreateOrConnectWithoutProductListInput'][] | null; // [ProductInProductListCreateOrConnectWithoutProductListInput!]
    create?: NexusGenInputs['ProductInProductListCreateWithoutProductListInput'][] | null; // [ProductInProductListCreateWithoutProductListInput!]
    createMany?: NexusGenInputs['ProductInProductListCreateManyProductListInputEnvelope'] | null; // ProductInProductListCreateManyProductListInputEnvelope
  }
  ProductInProductListCreateNestedOneWithoutDistributionsInput: { // input type
    connect?: NexusGenInputs['ProductInProductListWhereUniqueInput'] | null; // ProductInProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductInProductListCreateOrConnectWithoutDistributionsInput'] | null; // ProductInProductListCreateOrConnectWithoutDistributionsInput
    create?: NexusGenInputs['ProductInProductListCreateWithoutDistributionsInput'] | null; // ProductInProductListCreateWithoutDistributionsInput
  }
  ProductInProductListCreateOrConnectWithoutDistributionsInput: { // input type
    create: NexusGenInputs['ProductInProductListCreateWithoutDistributionsInput']; // ProductInProductListCreateWithoutDistributionsInput!
    where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
  }
  ProductInProductListCreateOrConnectWithoutProductListInput: { // input type
    create: NexusGenInputs['ProductInProductListCreateWithoutProductListInput']; // ProductInProductListCreateWithoutProductListInput!
    where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
  }
  ProductInProductListCreateWithoutDistributionsInput: { // input type
    exclusive?: string | null; // String
    exclusiveComments?: string | null; // String
    minimumOrderQuantity?: number | null; // Int
    product: NexusGenInputs['ProductCreateNestedOneWithoutProductListsInput']; // ProductCreateNestedOneWithoutProductListsInput!
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupCreateNestedOneWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateNestedOneWithoutProductInProductListInput
    productList: NexusGenInputs['ProductListCreateNestedOneWithoutProductsInput']; // ProductListCreateNestedOneWithoutProductsInput!
  }
  ProductInProductListCreateWithoutProductListInput: { // input type
    distributions?: NexusGenInputs['DistributionForProductInProductListCreateNestedManyWithoutProductInProductListInput'] | null; // DistributionForProductInProductListCreateNestedManyWithoutProductInProductListInput
    exclusive?: string | null; // String
    exclusiveComments?: string | null; // String
    minimumOrderQuantity?: number | null; // Int
    product: NexusGenInputs['ProductCreateNestedOneWithoutProductListsInput']; // ProductCreateNestedOneWithoutProductListsInput!
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupCreateNestedOneWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateNestedOneWithoutProductInProductListInput
  }
  ProductInProductListListRelationFilter: { // input type
    every?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
    none?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
    some?: NexusGenInputs['ProductInProductListWhereInput'] | null; // ProductInProductListWhereInput
  }
  ProductInProductListProductIdProductListIdCompoundUniqueInput: { // input type
    productId: number; // Int!
    productListId: number; // Int!
  }
  ProductInProductListScalarWhereInput: { // input type
    AND?: NexusGenInputs['ProductInProductListScalarWhereInput'][] | null; // [ProductInProductListScalarWhereInput!]
    NOT?: NexusGenInputs['ProductInProductListScalarWhereInput'][] | null; // [ProductInProductListScalarWhereInput!]
    OR?: NexusGenInputs['ProductInProductListScalarWhereInput'][] | null; // [ProductInProductListScalarWhereInput!]
    exclusive?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    exclusiveComments?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    minimumOrderQuantity?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    productId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productLifecycleGroupName?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    productListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ProductInProductListUpdateInput: { // input type
    distributions?: NexusGenInputs['DistributionForProductInProductListUpdateManyWithoutProductInProductListInput'] | null; // DistributionForProductInProductListUpdateManyWithoutProductInProductListInput
    exclusive?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    exclusiveComments?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    minimumOrderQuantity?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    product?: NexusGenInputs['ProductUpdateOneRequiredWithoutProductListsInput'] | null; // ProductUpdateOneRequiredWithoutProductListsInput
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupUpdateOneWithoutProductInProductListInput'] | null; // ProductLifecycleGroupUpdateOneWithoutProductInProductListInput
    productList?: NexusGenInputs['ProductListUpdateOneRequiredWithoutProductsInput'] | null; // ProductListUpdateOneRequiredWithoutProductsInput
  }
  ProductInProductListUpdateManyMutationInput: { // input type
    exclusive?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    exclusiveComments?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    minimumOrderQuantity?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
  }
  ProductInProductListUpdateManyWithWhereWithoutProductListInput: { // input type
    data: NexusGenInputs['ProductInProductListUpdateManyMutationInput']; // ProductInProductListUpdateManyMutationInput!
    where: NexusGenInputs['ProductInProductListScalarWhereInput']; // ProductInProductListScalarWhereInput!
  }
  ProductInProductListUpdateManyWithoutProductListInput: { // input type
    connect?: NexusGenInputs['ProductInProductListWhereUniqueInput'][] | null; // [ProductInProductListWhereUniqueInput!]
    connectOrCreate?: NexusGenInputs['ProductInProductListCreateOrConnectWithoutProductListInput'][] | null; // [ProductInProductListCreateOrConnectWithoutProductListInput!]
    create?: NexusGenInputs['ProductInProductListCreateWithoutProductListInput'][] | null; // [ProductInProductListCreateWithoutProductListInput!]
    createMany?: NexusGenInputs['ProductInProductListCreateManyProductListInputEnvelope'] | null; // ProductInProductListCreateManyProductListInputEnvelope
    delete?: NexusGenInputs['ProductInProductListWhereUniqueInput'][] | null; // [ProductInProductListWhereUniqueInput!]
    deleteMany?: NexusGenInputs['ProductInProductListScalarWhereInput'][] | null; // [ProductInProductListScalarWhereInput!]
    disconnect?: NexusGenInputs['ProductInProductListWhereUniqueInput'][] | null; // [ProductInProductListWhereUniqueInput!]
    set?: NexusGenInputs['ProductInProductListWhereUniqueInput'][] | null; // [ProductInProductListWhereUniqueInput!]
    update?: NexusGenInputs['ProductInProductListUpdateWithWhereUniqueWithoutProductListInput'][] | null; // [ProductInProductListUpdateWithWhereUniqueWithoutProductListInput!]
    updateMany?: NexusGenInputs['ProductInProductListUpdateManyWithWhereWithoutProductListInput'][] | null; // [ProductInProductListUpdateManyWithWhereWithoutProductListInput!]
    upsert?: NexusGenInputs['ProductInProductListUpsertWithWhereUniqueWithoutProductListInput'][] | null; // [ProductInProductListUpsertWithWhereUniqueWithoutProductListInput!]
  }
  ProductInProductListUpdateOneRequiredWithoutDistributionsInput: { // input type
    connect?: NexusGenInputs['ProductInProductListWhereUniqueInput'] | null; // ProductInProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductInProductListCreateOrConnectWithoutDistributionsInput'] | null; // ProductInProductListCreateOrConnectWithoutDistributionsInput
    create?: NexusGenInputs['ProductInProductListCreateWithoutDistributionsInput'] | null; // ProductInProductListCreateWithoutDistributionsInput
    update?: NexusGenInputs['ProductInProductListUpdateWithoutDistributionsInput'] | null; // ProductInProductListUpdateWithoutDistributionsInput
    upsert?: NexusGenInputs['ProductInProductListUpsertWithoutDistributionsInput'] | null; // ProductInProductListUpsertWithoutDistributionsInput
  }
  ProductInProductListUpdateRowInput: { // input type
    data: NexusGenInputs['ProductInProductListUpdateInput']; // ProductInProductListUpdateInput!
    where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
  }
  ProductInProductListUpdateWithWhereUniqueWithoutProductListInput: { // input type
    data: NexusGenInputs['ProductInProductListUpdateWithoutProductListInput']; // ProductInProductListUpdateWithoutProductListInput!
    where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
  }
  ProductInProductListUpdateWithoutDistributionsInput: { // input type
    exclusive?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    exclusiveComments?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    minimumOrderQuantity?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    product?: NexusGenInputs['ProductUpdateOneRequiredWithoutProductListsInput'] | null; // ProductUpdateOneRequiredWithoutProductListsInput
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupUpdateOneWithoutProductInProductListInput'] | null; // ProductLifecycleGroupUpdateOneWithoutProductInProductListInput
    productList?: NexusGenInputs['ProductListUpdateOneRequiredWithoutProductsInput'] | null; // ProductListUpdateOneRequiredWithoutProductsInput
  }
  ProductInProductListUpdateWithoutProductListInput: { // input type
    distributions?: NexusGenInputs['DistributionForProductInProductListUpdateManyWithoutProductInProductListInput'] | null; // DistributionForProductInProductListUpdateManyWithoutProductInProductListInput
    exclusive?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    exclusiveComments?: NexusGenInputs['NullableStringFieldUpdateOperationsInput'] | null; // NullableStringFieldUpdateOperationsInput
    minimumOrderQuantity?: NexusGenInputs['NullableIntFieldUpdateOperationsInput'] | null; // NullableIntFieldUpdateOperationsInput
    product?: NexusGenInputs['ProductUpdateOneRequiredWithoutProductListsInput'] | null; // ProductUpdateOneRequiredWithoutProductListsInput
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupUpdateOneWithoutProductInProductListInput'] | null; // ProductLifecycleGroupUpdateOneWithoutProductInProductListInput
  }
  ProductInProductListUpsertWithWhereUniqueWithoutProductListInput: { // input type
    create: NexusGenInputs['ProductInProductListCreateWithoutProductListInput']; // ProductInProductListCreateWithoutProductListInput!
    update: NexusGenInputs['ProductInProductListUpdateWithoutProductListInput']; // ProductInProductListUpdateWithoutProductListInput!
    where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
  }
  ProductInProductListUpsertWithoutDistributionsInput: { // input type
    create: NexusGenInputs['ProductInProductListCreateWithoutDistributionsInput']; // ProductInProductListCreateWithoutDistributionsInput!
    update: NexusGenInputs['ProductInProductListUpdateWithoutDistributionsInput']; // ProductInProductListUpdateWithoutDistributionsInput!
  }
  ProductInProductListWhereInput: { // input type
    AND?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    NOT?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    OR?: NexusGenInputs['ProductInProductListWhereInput'][] | null; // [ProductInProductListWhereInput!]
    distributions?: NexusGenInputs['DistributionForProductInProductListListRelationFilter'] | null; // DistributionForProductInProductListListRelationFilter
    exclusive?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    exclusiveComments?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    minimumOrderQuantity?: NexusGenInputs['IntNullableFilter'] | null; // IntNullableFilter
    product?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    productId?: NexusGenInputs['IntFilter'] | null; // IntFilter
    productLifecycleGroup?: NexusGenInputs['ProductLifecycleGroupWhereInput'] | null; // ProductLifecycleGroupWhereInput
    productLifecycleGroupName?: NexusGenInputs['StringNullableFilter'] | null; // StringNullableFilter
    productList?: NexusGenInputs['ProductListWhereInput'] | null; // ProductListWhereInput
    productListId?: NexusGenInputs['IntFilter'] | null; // IntFilter
  }
  ProductInProductListWhereUniqueInput: { // input type
    id?: number | null; // Int
    productId_productListId?: NexusGenInputs['ProductInProductListProductIdProductListIdCompoundUniqueInput'] | null; // ProductInProductListProductIdProductListIdCompoundUniqueInput
  }
  ProductLifecycleGroupCreateNestedOneWithoutProductInProductListInput: { // input type
    connect?: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput'] | null; // ProductLifecycleGroupWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductLifecycleGroupCreateOrConnectWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateOrConnectWithoutProductInProductListInput
    create?: NexusGenInputs['ProductLifecycleGroupCreateWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateWithoutProductInProductListInput
  }
  ProductLifecycleGroupCreateOrConnectWithoutProductInProductListInput: { // input type
    create: NexusGenInputs['ProductLifecycleGroupCreateWithoutProductInProductListInput']; // ProductLifecycleGroupCreateWithoutProductInProductListInput!
    where: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput']; // ProductLifecycleGroupWhereUniqueInput!
  }
  ProductLifecycleGroupCreateWithoutProductInProductListInput: { // input type
    displayName: string; // String!
    name: string; // String!
  }
  ProductLifecycleGroupUpdateOneWithoutProductInProductListInput: { // input type
    connect?: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput'] | null; // ProductLifecycleGroupWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductLifecycleGroupCreateOrConnectWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateOrConnectWithoutProductInProductListInput
    create?: NexusGenInputs['ProductLifecycleGroupCreateWithoutProductInProductListInput'] | null; // ProductLifecycleGroupCreateWithoutProductInProductListInput
    delete?: boolean | null; // Boolean
    disconnect?: boolean | null; // Boolean
    update?: NexusGenInputs['ProductLifecycleGroupUpdateWithoutProductInProductListInput'] | null; // ProductLifecycleGroupUpdateWithoutProductInProductListInput
    upsert?: NexusGenInputs['ProductLifecycleGroupUpsertWithoutProductInProductListInput'] | null; // ProductLifecycleGroupUpsertWithoutProductInProductListInput
  }
  ProductLifecycleGroupUpdateWithoutProductInProductListInput: { // input type
    displayName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    name?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProductLifecycleGroupUpsertWithoutProductInProductListInput: { // input type
    create: NexusGenInputs['ProductLifecycleGroupCreateWithoutProductInProductListInput']; // ProductLifecycleGroupCreateWithoutProductInProductListInput!
    update: NexusGenInputs['ProductLifecycleGroupUpdateWithoutProductInProductListInput']; // ProductLifecycleGroupUpdateWithoutProductInProductListInput!
  }
  ProductLifecycleGroupWhereInput: { // input type
    AND?: NexusGenInputs['ProductLifecycleGroupWhereInput'][] | null; // [ProductLifecycleGroupWhereInput!]
    NOT?: NexusGenInputs['ProductLifecycleGroupWhereInput'][] | null; // [ProductLifecycleGroupWhereInput!]
    OR?: NexusGenInputs['ProductLifecycleGroupWhereInput'][] | null; // [ProductLifecycleGroupWhereInput!]
    ProductInProductList?: NexusGenInputs['ProductInProductListListRelationFilter'] | null; // ProductInProductListListRelationFilter
    displayName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    name?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductLifecycleGroupWhereUniqueInput: { // input type
    displayName?: string | null; // String
    name?: string | null; // String
  }
  ProductListCreateNestedOneWithoutChannelsInput: { // input type
    connect?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductListCreateOrConnectWithoutChannelsInput'] | null; // ProductListCreateOrConnectWithoutChannelsInput
    create?: NexusGenInputs['ProductListCreateWithoutChannelsInput'] | null; // ProductListCreateWithoutChannelsInput
  }
  ProductListCreateNestedOneWithoutProductsInput: { // input type
    connect?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductListCreateOrConnectWithoutProductsInput'] | null; // ProductListCreateOrConnectWithoutProductsInput
    create?: NexusGenInputs['ProductListCreateWithoutProductsInput'] | null; // ProductListCreateWithoutProductsInput
  }
  ProductListCreateOrConnectWithoutChannelsInput: { // input type
    create: NexusGenInputs['ProductListCreateWithoutChannelsInput']; // ProductListCreateWithoutChannelsInput!
    where: NexusGenInputs['ProductListWhereUniqueInput']; // ProductListWhereUniqueInput!
  }
  ProductListCreateOrConnectWithoutProductsInput: { // input type
    create: NexusGenInputs['ProductListCreateWithoutProductsInput']; // ProductListCreateWithoutProductsInput!
    where: NexusGenInputs['ProductListWhereUniqueInput']; // ProductListWhereUniqueInput!
  }
  ProductListCreateWithoutChannelsInput: { // input type
    products?: NexusGenInputs['ProductInProductListCreateNestedManyWithoutProductListInput'] | null; // ProductInProductListCreateNestedManyWithoutProductListInput
    title: string; // String!
  }
  ProductListCreateWithoutProductsInput: { // input type
    channels?: NexusGenInputs['ChannelInProductListCreateNestedManyWithoutProductListInput'] | null; // ChannelInProductListCreateNestedManyWithoutProductListInput
    title: string; // String!
  }
  ProductListUpdateOneRequiredWithoutChannelsInput: { // input type
    connect?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductListCreateOrConnectWithoutChannelsInput'] | null; // ProductListCreateOrConnectWithoutChannelsInput
    create?: NexusGenInputs['ProductListCreateWithoutChannelsInput'] | null; // ProductListCreateWithoutChannelsInput
    update?: NexusGenInputs['ProductListUpdateWithoutChannelsInput'] | null; // ProductListUpdateWithoutChannelsInput
    upsert?: NexusGenInputs['ProductListUpsertWithoutChannelsInput'] | null; // ProductListUpsertWithoutChannelsInput
  }
  ProductListUpdateOneRequiredWithoutProductsInput: { // input type
    connect?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductListCreateOrConnectWithoutProductsInput'] | null; // ProductListCreateOrConnectWithoutProductsInput
    create?: NexusGenInputs['ProductListCreateWithoutProductsInput'] | null; // ProductListCreateWithoutProductsInput
    update?: NexusGenInputs['ProductListUpdateWithoutProductsInput'] | null; // ProductListUpdateWithoutProductsInput
    upsert?: NexusGenInputs['ProductListUpsertWithoutProductsInput'] | null; // ProductListUpsertWithoutProductsInput
  }
  ProductListUpdateWithoutChannelsInput: { // input type
    products?: NexusGenInputs['ProductInProductListUpdateManyWithoutProductListInput'] | null; // ProductInProductListUpdateManyWithoutProductListInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProductListUpdateWithoutProductsInput: { // input type
    channels?: NexusGenInputs['ChannelInProductListUpdateManyWithoutProductListInput'] | null; // ChannelInProductListUpdateManyWithoutProductListInput
    title?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProductListUpsertWithoutChannelsInput: { // input type
    create: NexusGenInputs['ProductListCreateWithoutChannelsInput']; // ProductListCreateWithoutChannelsInput!
    update: NexusGenInputs['ProductListUpdateWithoutChannelsInput']; // ProductListUpdateWithoutChannelsInput!
  }
  ProductListUpsertWithoutProductsInput: { // input type
    create: NexusGenInputs['ProductListCreateWithoutProductsInput']; // ProductListCreateWithoutProductsInput!
    update: NexusGenInputs['ProductListUpdateWithoutProductsInput']; // ProductListUpdateWithoutProductsInput!
  }
  ProductListWhereInput: { // input type
    AND?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    NOT?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    OR?: NexusGenInputs['ProductListWhereInput'][] | null; // [ProductListWhereInput!]
    channels?: NexusGenInputs['ChannelInProductListListRelationFilter'] | null; // ChannelInProductListListRelationFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    products?: NexusGenInputs['ProductInProductListListRelationFilter'] | null; // ProductInProductListListRelationFilter
    title?: NexusGenInputs['StringFilter'] | null; // StringFilter
  }
  ProductListWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  ProductUpdateOneRequiredWithoutProductListsInput: { // input type
    connect?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
    connectOrCreate?: NexusGenInputs['ProductCreateOrConnectWithoutProductListsInput'] | null; // ProductCreateOrConnectWithoutProductListsInput
    create?: NexusGenInputs['ProductCreateWithoutProductListsInput'] | null; // ProductCreateWithoutProductListsInput
    update?: NexusGenInputs['ProductUpdateWithoutProductListsInput'] | null; // ProductUpdateWithoutProductListsInput
    upsert?: NexusGenInputs['ProductUpsertWithoutProductListsInput'] | null; // ProductUpsertWithoutProductListsInput
  }
  ProductUpdateWithoutProductListsInput: { // input type
    colorwayName?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
    pc9?: NexusGenInputs['StringFieldUpdateOperationsInput'] | null; // StringFieldUpdateOperationsInput
  }
  ProductUpsertWithoutProductListsInput: { // input type
    create: NexusGenInputs['ProductCreateWithoutProductListsInput']; // ProductCreateWithoutProductListsInput!
    update: NexusGenInputs['ProductUpdateWithoutProductListsInput']; // ProductUpdateWithoutProductListsInput!
  }
  ProductWhereInput: { // input type
    AND?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    NOT?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    OR?: NexusGenInputs['ProductWhereInput'][] | null; // [ProductWhereInput!]
    colorwayName?: NexusGenInputs['StringFilter'] | null; // StringFilter
    id?: NexusGenInputs['IntFilter'] | null; // IntFilter
    pc9?: NexusGenInputs['StringFilter'] | null; // StringFilter
    productLists?: NexusGenInputs['ProductInProductListListRelationFilter'] | null; // ProductInProductListListRelationFilter
  }
  ProductWhereUniqueInput: { // input type
    id?: number | null; // Int
  }
  StringFieldUpdateOperationsInput: { // input type
    set?: string | null; // String
  }
  StringFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringFilter'] | null; // NestedStringFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
  StringNullableFilter: { // input type
    contains?: string | null; // String
    endsWith?: string | null; // String
    equals?: string | null; // String
    gt?: string | null; // String
    gte?: string | null; // String
    in?: string[] | null; // [String!]
    lt?: string | null; // String
    lte?: string | null; // String
    mode?: NexusGenEnums['QueryMode'] | null; // QueryMode
    not?: NexusGenInputs['NestedStringNullableFilter'] | null; // NestedStringNullableFilter
    notIn?: string[] | null; // [String!]
    startsWith?: string | null; // String
  }
}

export interface NexusGenEnums {
  QueryMode: "default" | "insensitive"
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  Channel: { // root type
    name: string; // String!
  }
  ChannelInProductList: {};
  Distribution: { // root type
    name: string; // String!
  }
  DistributionForProductInProductList: {};
  Mutation: {};
  PageInfo: { // root type
    endCursor?: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor?: string | null; // String
  }
  Product: { // root type
    colorwayName: string; // String!
    pc9: string; // String!
  }
  ProductInProductList: { // root type
    exclusive?: string | null; // String
    exclusiveComments?: string | null; // String
    minimumOrderQuantity?: number | null; // Int
  }
  ProductLifecycleGroup: { // root type
    displayName: string; // String!
    name: string; // String!
  }
  ProductList: { // root type
    title: string; // String!
  }
  ProductListProduct: { // root type
    product: NexusGenRootTypes['Product']; // Product!
    productInProductList: NexusGenRootTypes['ProductInProductList']; // ProductInProductList!
  }
  ProductListProductConnection: { // root type
    edges: NexusGenRootTypes['ProductListProductEdge'][]; // [ProductListProductEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  ProductListProductEdge: { // root type
    cursor: string; // String!
    node: NexusGenRootTypes['ProductListProduct']; // ProductListProduct!
  }
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars & NexusGenEnums

export interface NexusGenFieldTypes {
  Channel: { // field return type
    id: string; // ID!
    name: string; // String!
    ownId: number; // Int!
  }
  ChannelInProductList: { // field return type
    channel: NexusGenRootTypes['Channel']; // Channel!
    id: string; // ID!
    ownId: number; // Int!
  }
  Distribution: { // field return type
    channel: NexusGenRootTypes['Channel']; // Channel!
    id: string; // ID!
    name: string; // String!
    ownId: number; // Int!
  }
  DistributionForProductInProductList: { // field return type
    distribution: NexusGenRootTypes['Distribution']; // Distribution!
    id: string; // ID!
    ownId: number; // Int!
  }
  Mutation: { // field return type
    updateManyProductInProductList: NexusGenRootTypes['ProductInProductList'][]; // [ProductInProductList!]!
    updateOneProductInProductList: NexusGenRootTypes['ProductInProductList'] | null; // ProductInProductList
  }
  PageInfo: { // field return type
    endCursor: string | null; // String
    hasNextPage: boolean; // Boolean!
    hasPreviousPage: boolean; // Boolean!
    startCursor: string | null; // String
  }
  Product: { // field return type
    colorwayName: string; // String!
    id: string; // ID!
    ownId: number; // Int!
    pc9: string; // String!
  }
  ProductInProductList: { // field return type
    distributions: NexusGenRootTypes['DistributionForProductInProductList'][]; // [DistributionForProductInProductList!]!
    exclusive: string | null; // String
    exclusiveComments: string | null; // String
    id: string; // ID!
    minimumOrderQuantity: number | null; // Int
    ownId: number; // Int!
    productLifecycleGroup: NexusGenRootTypes['ProductLifecycleGroup'] | null; // ProductLifecycleGroup
  }
  ProductLifecycleGroup: { // field return type
    displayName: string; // String!
    name: string; // String!
  }
  ProductList: { // field return type
    channels: NexusGenRootTypes['ChannelInProductList'][]; // [ChannelInProductList!]!
    id: string; // ID!
    ownId: number; // Int!
    productListProductConnection: NexusGenRootTypes['ProductListProductConnection']; // ProductListProductConnection!
    title: string; // String!
  }
  ProductListProduct: { // field return type
    id: string; // ID!
    product: NexusGenRootTypes['Product']; // Product!
    productInProductList: NexusGenRootTypes['ProductInProductList']; // ProductInProductList!
  }
  ProductListProductConnection: { // field return type
    edges: NexusGenRootTypes['ProductListProductEdge'][]; // [ProductListProductEdge!]!
    pageInfo: NexusGenRootTypes['PageInfo']; // PageInfo!
  }
  ProductListProductEdge: { // field return type
    cursor: string; // String!
    node: NexusGenRootTypes['ProductListProduct']; // ProductListProduct!
  }
  Query: { // field return type
    product: NexusGenRootTypes['Product'] | null; // Product
    productLifecycleGroup: NexusGenRootTypes['ProductLifecycleGroup'] | null; // ProductLifecycleGroup
    productLifecycleGroups: NexusGenRootTypes['ProductLifecycleGroup'][]; // [ProductLifecycleGroup!]!
    productList: NexusGenRootTypes['ProductList'] | null; // ProductList
    productLists: NexusGenRootTypes['ProductList'][]; // [ProductList!]!
    products: NexusGenRootTypes['Product'][]; // [Product!]!
  }
}

export interface NexusGenFieldTypeNames {
  Channel: { // field return type name
    id: 'ID'
    name: 'String'
    ownId: 'Int'
  }
  ChannelInProductList: { // field return type name
    channel: 'Channel'
    id: 'ID'
    ownId: 'Int'
  }
  Distribution: { // field return type name
    channel: 'Channel'
    id: 'ID'
    name: 'String'
    ownId: 'Int'
  }
  DistributionForProductInProductList: { // field return type name
    distribution: 'Distribution'
    id: 'ID'
    ownId: 'Int'
  }
  Mutation: { // field return type name
    updateManyProductInProductList: 'ProductInProductList'
    updateOneProductInProductList: 'ProductInProductList'
  }
  PageInfo: { // field return type name
    endCursor: 'String'
    hasNextPage: 'Boolean'
    hasPreviousPage: 'Boolean'
    startCursor: 'String'
  }
  Product: { // field return type name
    colorwayName: 'String'
    id: 'ID'
    ownId: 'Int'
    pc9: 'String'
  }
  ProductInProductList: { // field return type name
    distributions: 'DistributionForProductInProductList'
    exclusive: 'String'
    exclusiveComments: 'String'
    id: 'ID'
    minimumOrderQuantity: 'Int'
    ownId: 'Int'
    productLifecycleGroup: 'ProductLifecycleGroup'
  }
  ProductLifecycleGroup: { // field return type name
    displayName: 'String'
    name: 'String'
  }
  ProductList: { // field return type name
    channels: 'ChannelInProductList'
    id: 'ID'
    ownId: 'Int'
    productListProductConnection: 'ProductListProductConnection'
    title: 'String'
  }
  ProductListProduct: { // field return type name
    id: 'ID'
    product: 'Product'
    productInProductList: 'ProductInProductList'
  }
  ProductListProductConnection: { // field return type name
    edges: 'ProductListProductEdge'
    pageInfo: 'PageInfo'
  }
  ProductListProductEdge: { // field return type name
    cursor: 'String'
    node: 'ProductListProduct'
  }
  Query: { // field return type name
    product: 'Product'
    productLifecycleGroup: 'ProductLifecycleGroup'
    productLifecycleGroups: 'ProductLifecycleGroup'
    productList: 'ProductList'
    productLists: 'ProductList'
    products: 'Product'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    updateManyProductInProductList: { // args
      data?: NexusGenInputs['ProductInProductListUpdateRowInput'][] | null; // [ProductInProductListUpdateRowInput!]
    }
    updateOneProductInProductList: { // args
      data: NexusGenInputs['ProductInProductListUpdateInput']; // ProductInProductListUpdateInput!
      where: NexusGenInputs['ProductInProductListWhereUniqueInput']; // ProductInProductListWhereUniqueInput!
    }
  }
  ProductInProductList: {
    distributions: { // args
      after?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'] | null; // DistributionForProductInProductListWhereUniqueInput
      before?: NexusGenInputs['DistributionForProductInProductListWhereUniqueInput'] | null; // DistributionForProductInProductListWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  ProductList: {
    channels: { // args
      after?: NexusGenInputs['ChannelInProductListWhereUniqueInput'] | null; // ChannelInProductListWhereUniqueInput
      before?: NexusGenInputs['ChannelInProductListWhereUniqueInput'] | null; // ChannelInProductListWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
    }
    productListProductConnection: { // args
      after?: string | null; // String
      before?: string | null; // String
      first?: number | null; // Int
      last?: number | null; // Int
    }
  }
  Query: {
    product: { // args
      where: NexusGenInputs['ProductWhereUniqueInput']; // ProductWhereUniqueInput!
    }
    productLifecycleGroup: { // args
      where: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput']; // ProductLifecycleGroupWhereUniqueInput!
    }
    productLifecycleGroups: { // args
      after?: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput'] | null; // ProductLifecycleGroupWhereUniqueInput
      before?: NexusGenInputs['ProductLifecycleGroupWhereUniqueInput'] | null; // ProductLifecycleGroupWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['ProductLifecycleGroupWhereInput'] | null; // ProductLifecycleGroupWhereInput
    }
    productList: { // args
      where: NexusGenInputs['ProductListWhereUniqueInput']; // ProductListWhereUniqueInput!
    }
    productLists: { // args
      after?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
      before?: NexusGenInputs['ProductListWhereUniqueInput'] | null; // ProductListWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['ProductListWhereInput'] | null; // ProductListWhereInput
    }
    products: { // args
      after?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
      before?: NexusGenInputs['ProductWhereUniqueInput'] | null; // ProductWhereUniqueInput
      first?: number | null; // Int
      last?: number | null; // Int
      where?: NexusGenInputs['ProductWhereInput'] | null; // ProductWhereInput
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = keyof NexusGenInputs;

export type NexusGenEnumNames = keyof NexusGenEnums;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
    
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}